# Generated by Django 4.2.4 on 2023-08-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="email_id",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
